
name: "Update Post"

on:
  schedule:
    - cron: "10 */1 * * *" # At the 10th minute every hour to hopefully schedule on time
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check post changes
      run: |
        pip3 install -r requirements.txt
        python3 poll.py
    - name: Commit changes if any
      run: |
        git config --local user.email github-actions@github.com
        git config --local user.name github-actions
        echo `git commit -am "[$(date)] Automated update."`
        git push
